remove gradle
rsocket/rsocket-website pull request #38
Opened 2021-03-02 03:13 UTC by flyinprogrammer

flatten directories

move content into content- folders

update documentation based on changes

2021-03-02 03:45 UTC, viglucci commented
Would be nice to land this into master than then rebase #29 on it since most of the changes are unrelated to #29 and im not sure when #29 will land.

Would you be able to change the PR base to master and just remove my work in progress page additions? I can worry about rebasing #29 onto master after that.

2021-03-02 03:45 UTC, viglucci requested changes
Would be nice to land this into master than then rebase #29 on it since most of the changes are unrelated to #29 and im not sure when #29 will land.

Would you be able to change the PR base to master and just remove my work in progress page additions? I can worry about rebasing #29 onto master after that.

2021-03-02 03:48 UTC, viglucci commented
On second thought I'll make the changes to remove my work in-progress page. Should be minimal change, then we can change the PR base to master.

2021-03-02 03:58 UTC, viglucci commented
> On second thought I'll make the changes to remove my work in-progress page. Should be minimal change, then we can change the PR base to master.

Addressed here: https://github.com/rsocket/rsocket-website/pull/40.

If we land that then we can land this in master without worrying about #29 while its in-progress.

2021-03-02 16:10 UTC, flyinprogrammer commented
This is now ready for review again. I _believe_ when it lands in `master` the Github Action will work correctly and publish the site.

2021-03-02 23:47 UTC, viglucci commented on CONTRIBUTING.md
> +what will that value be for contributors or people who want to fork ¯\_(ツ)_/¯
I think this `TODO` is now complete?

2021-03-02 23:51 UTC, viglucci approved these changes

2021-03-02 23:52 UTC, merged

2021-03-03 00:04 UTC, flyinprogrammer commented on CONTRIBUTING.md
> +what will that value be for contributors or people who want to fork ¯\_(ツ)_/¯
not really i was waiting for things to roll on to master so i could then use the fork->PR process to fix it :joy: